# Spliting Code
* Video Wise Split
* Extract Unique Videos
* 70% Train, 15% Val, 15% Test
* Add 'split' column back into main dataframe
* Save Updated Manifest

In [1]:
import pandas as pd
import os, math, random
from pathlib import Path
from sklearn.model_selection import train_test_split

In [2]:
BASE_DIR = Path().resolve().parents[0]

csv_path = BASE_DIR / 'data' / 'processed' / 'manifest.csv'

df = pd.read_csv(csv_path)
df.head()

                                          image_path  label video_id
0  /home/aryan/code/DeepFakeDetection/data/proces...      0      360
1  /home/aryan/code/DeepFakeDetection/data/proces...      0      360
2  /home/aryan/code/DeepFakeDetection/data/proces...      0      360
3  /home/aryan/code/DeepFakeDetection/data/proces...      0      360
4  /home/aryan/code/DeepFakeDetection/data/proces...      0      360

## Extract Unique Videos

In [3]:
video_df = df[['video_id', 'label']].drop_duplicates()

video_df.head()

    video_id  label
0        360      0
77       942      0
176      183      0
254      609      0
352      071      0

## 70% Train, 15% Val, 15% Test

In [4]:
# Train split
train_vids, temp_vids = train_test_split(
    video_df,
    test_size=0.30,
    stratify=video_df['label'],
    random_state=1
)

# Validation + Test split
val_vids, test_vids = train_test_split(
    temp_vids,
    test_size=0.50,
    stratify=temp_vids['label'],
    random_state=1
)

## Add 'split' column back into main dataframe

In [5]:
df['split'] = None
df.loc[df['video_id'].isin(train_vids['video_id']), 'split'] = 'train'
df.loc[df['video_id'].isin(val_vids['video_id']), 'split'] = 'val'
df.loc[df['video_id'].isin(test_vids['video_id']), 'split'] = 'test'

df.split.value_counts()

split
train    23358
test      4907
val       4787
Name: count, dtype: int64

## Save Updated Manifest

In [6]:
df.to_csv(csv_path, index=False)
print("Updated manifest saved.")

Updated manifest saved.

In [7]:
df.head()

                                          image_path  label video_id  split
0  /home/aryan/code/DeepFakeDetection/data/proces...      0      360  train
1  /home/aryan/code/DeepFakeDetection/data/proces...      0      360  train
2  /home/aryan/code/DeepFakeDetection/data/proces...      0      360  train
3  /home/aryan/code/DeepFakeDetection/data/proces...      0      360  train
4  /home/aryan/code/DeepFakeDetection/data/proces...      0      360  train